server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: api-key-management-demo
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DB_USER:local_postgres}
    password: ${DB_PASSWORD:local_postgres}

  security:
    user:
      name: user
      password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  sleuth:
    jdbc:
      p6spy:
        tracing:
          include-parameter-values: true

jwt:
  secret: ${JWT_SECRET:90bf33c9c3576793ee92dc07563b621d}

# p6spy 설정 추가
decorator:
  datasource:
    p6spy:
      enable: true
      enable-logging: true
      multiline: true
      logging: slf4j

logging:
  level:
    root: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    p6spy: debug
