server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: api-key-management-demo

  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2

jwt:
  secret: ${JWT_SECRET:90bf33c9c3576793ee92dc07563b621d}
