server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8

spring:
  application:
    name: api-key-management-demo

  # DB properties
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:33304/postgres?currentSchema=public&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:mypassword}
