server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
spring:
  application:
    name: api-key-management-demo
  datasource:
    driver-class-name: org.h2.Driver
    url: ${DB_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    username: ${DB_USER:sa}
    password: ${DB_PASSWORD:}

  security:
    user:
      name: user
      password: password

  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      username: ${DB_USER:sa}
      password: ${DB_PASSWORD:}
      schema-locations: file:db/schema.sql
      #data-locations: file:db/data.sql

jwt:
  secret: ${JWT_SECRET:90bf33c9c3576793ee92dc07563b621d}
